---
kind: Template
apiVersion: v1
metadata:
  name: opennebula-node
labels:
  template: one-node
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: "${ONE_SERVICE_NAME}"
    creationTimestamp:
  spec:
    ports:
    - name: onenode
      port: 2222
      targetPort: 2222
    selector:
      name: "${ONE_SERVICE_NAME}"
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${ONE_SERVICE_NAME}"
    creationTimestamp:
  spec:
    restartPolicy: Never
    replicas: 1
    selector:
      name: "${ONE_SERVICE_NAME}"
    template:
      metadata:
        creationTimestamp:
        labels:
          name: "${ONE_SERVICE_NAME}"
      spec:
        containers:
        - name: onenode
          image: "megamio/docker_onenode:latest"
          imagePullPolicy: "IfNotPresent"
          env:
          - name: ssh_public
            valueFrom:
              secretKeyRef:
                name: ssh
                key: ssh-publickey
          ports:
          - containerPort: 2222
          resources:
            limits:
              memory: "${MEMORY_LIMIT}"
        volumeMounts:
         - name: "libvirt-lib"
           mountPath: "/var/lib/libvirt/"
         - name: "libvirt-run"
           mountPath: "/var/run/libvirt/"
         - name: "dbus-run"
           mountPath: "/var/run/dbus/"
         - name: "ceph-conf"
           mountPath: "/etc/ceph"
         - name: "ceph-lib"
           mountPath: "/var/lib/ceph/"
         - name: "datastore-data"
           mountPath: "/var/lib/one/datastores/"

        volumes:
        - name: "libvirt-lib"
          emptyDir: {}
        - name: "libvirt-run"
          emptyDir: {}
        - name: "ceph-conf"
          emptyDir: {}
        - name: "ceph-lib"
          emptyDir: {}
        - name: "datastore-data"
          emptyDir: {}
  status: {}
parameters:
- name: ONE_SERVICE_NAME
  displayName: OpenNebula Service Name
  description: The name of the ABCD Service exposed for OpenNebula.
  value: onenode
  required: true
- name: MEMORY_LIMIT
  displayName: Memory Limit
  description: Maximum amount of memory the container can use.
  value: 512Mi
  required: true
